class NidoDaemonError(Exception):
    """Exception class for errors generated by the Nido daemon
    process.
    """

    def __init__(self, msg):
        self.msg = msg
        return

    def __str__(self):
        return repr(self.msg)


class SchedulerClientError(NidoDaemonError):
    """Exception class for errors generated by the daemon scheduler RPC
    service.
    """


class ControllerError(NidoDaemonError):
    """Exception class for errors generated by the hardware
    controller.
    """


class ThermostatError(NidoDaemonError):
    """Exception class for errors generated by the thermostat."""
