version: "3.4"
services:
  nido-api:
    build:
      context: .
      target: nido-api
    ports:
      - "80:80"
    environment:
      - FLASK_APP=nido.web
      - FLASK_DEBUG=TRUE
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80
      - NIDO_DEBUG=""
      - NIDOD_RPC_HOST=nido-supervisor
    volumes:
      - ./nido:/app/nido
    entrypoint:
      - flask
      - run
      - --without-threads
  nido-supervisor:
    build:
      context: .
      target: nido-supervisor
    environment:
      - NIDO_TESTING_GPIO=/tmp/gpio_pins.yaml
      - NIDO_TESTING=""
    volumes:
      - ./instance:/app/instance
      - ./log:/app/log
      - ./nido:/app/nido
  
