version: "3.4"
services:
  nido-api:
    build:
      context: .
      target: nido-api
    ports:
      - "80:80"
  nido-daemon:
    build:
      context: .
      target: nido-daemon
    environment:
      - NIDO_TESTING=""
      - NIDO_TESTING_GPIO=/tmp/gpio_pins.yaml
  mosquitto:
    build:
      context: .
      target: nido-mqtt
    ports:
      - "1883:1883"
