version: "3.4"
services:
  nido-api:
    build:
      context: .
      target: nido-api
    ports:
      - "80:80"
    environment:
      - FLASK_APP=nido.web
      - FLASK_DEBUG=TRUE
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80
      - NIDO_DEBUG=""
      - NIDOD_RPC_HOST=nido-supervisor
      - NIDOD_MQTT_HOSTNAME=mosquitto
    volumes:
      - ./config:/app/instance
      - ./nido:/app/nido
    entrypoint:
      - flask
      - run
      - --without-threads
  nido-supervisor:
    build:
      context: .
      target: nido-supervisor
    volumes:
      - ./instance:/app/instance
      - ./log:/app/log
      - ./nido:/app/nido
  mosquitto:
    build:
      context: ./mqtt
      target: nido-mqtt
    ports:
      - "1883:1883"
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    volumes:
      - ./homebridge:/homebridge
    environment:
      - TZ=America/Los_Angeles
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    ports:
      - "8080:8080"
