GPIO:
        heat_pin: 26
        cool_pin: 20
behavior:
        hysteresis_c: 1
        hysteresis_f: 1
flask:
        port: 8080
        debug: False
        secret_key: some-very-long-string
        username: your-user
        password: your-password
wunderground:
        api_key: your-api-key-from-wunderground
db:
        schema: /home/user/nido/db/schema.sql
        database: /home/user/nido/db/nido.db
