GPIO:
    heat_pin: 26
    cool_pin: 20
behavior:
    hysteresis: 0.6
flask:
    port: 443
    secret_key: your-secret-key
    public_api_secret: your-secret-key
    username: your-username
    password: your-password
wunderground:
    api_key: your-api-key
google:
    api_key: your-api-key
daemon:
    pid_file: /tmp/nido.pid
    work_dir: /tmp
    log_file: /var/log/nidod.log
schedule:
    poll_interval: 300
    db: /absolute/path/to/app/db/nido.db
