from enum import Enum


class Mode(Enum):
    Off = 0
    Heat = 1
    Cool = 2
    Heat_Cool = 3


class Status(Enum):
    Off = 0
    Heating = 1
    Cooling = 2


class NidoDaemonError(Exception):
    """Exception class for errors generated by the Nido daemon
    process.
    """

    def __init__(self, msg):
        self.msg = msg
        return

    def __str__(self):
        return repr(self.msg)


class DBError(NidoDaemonError):
    """Exception class for error generated by the database interface."""


class SchedulerClientError(NidoDaemonError):
    """Exception class for errors generated by the daemon scheduler RPC
    service.
    """


class ThermostatClientError(NidoDaemonError):
    """Exception class for errors generated by the daemon thermostat RPC
    service.
    """


class ControllerError(NidoDaemonError):
    """Exception class for errors generated by the hardware
    controller.
    """


class SensorError(NidoDaemonError):
    """Exception class for errors generated by the hardware
    sensor.
    """


class ThermostatError(NidoDaemonError):
    """Exception class for errors generated by the thermostat."""
